import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

/**
 * Compose static/lockup.svg and static/lockup-inverse.svg.
 *
 * Run with `npm run lockup`. Only needed if the mark geometry or the name changes — the
 * output is committed.
 *
 * The wordmark arrives from scripts/wordmark.json as ready-made path coordinates, outlined
 * once from an open font. No font is read here, none is downloaded and none is shipped:
 * that is what makes the lockup render identically in a browser, in a print shop's layout
 * tool, or anywhere else an SVG is opened. Set as <text> it would fall back to whatever font
 * the viewer happened to have, which is the incoherence a lockup exists to prevent.
 */
const here = dirname(fileURLToPath(import.meta.url));
const { provenance, S, wordD, box } = JSON.parse(readFileSync(join(here, 'wordmark.json'), 'utf8'));

/*
 * Mark geometry, shared with the icons. Its own bounding box, worked out from the paths:
 * x 218..383, y 157..419 — 165 wide, 262 tall.
 */
const MARK = {
	d: ['M256 396 V180', 'M256 296 L360 200'],
	bud: { cx: 256, cy: 296, r: 38 },
	stroke: 46,
	x1: 218,
	y1: 157,
	x2: 383,
	y2: 419
};
const markW = MARK.x2 - MARK.x1;
const markH = MARK.y2 - MARK.y1;

const wordW = box.x2 - box.x1;
const wordH = box.y2 - box.y1;

// The mark stands a little taller than the capitals, and the gap is deliberately tight —
// the two parts should read as one lockup, not as an icon sitting next to a word.
const targetMarkH = wordH * 1.32;
const scale = targetMarkH / markH;
const gap = wordH * 0.11;

const scaledMarkW = markW * scale;
const pad = wordH * 0.1;

const totalW = scaledMarkW + gap + wordW;
const totalH = Math.max(targetMarkH, wordH);

// Baseline y such that the word block is vertically centred in the canvas.
const wordY = pad + (totalH - wordH) / 2 - box.y1;
// Both axes need the mark's own origin subtracted: its bounding box starts at (218, 157)
// in the shared coordinate space, not at (0, 0). Offsetting only y left the mark sitting
// 165 units to the right, printed over the G.
const markX = pad - MARK.x1 * scale;
const markY = pad + (totalH - targetMarkH) / 2 - MARK.y1 * scale;

const svg = (
	fg,
	name
) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${(totalW + pad * 2).toFixed(1)} ${(totalH + pad * 2).toFixed(1)}" role="img" aria-label="Graftful">
  <title>Graftful</title>
  <!--
    The lockup: mark and name as one asset, so the spacing between them cannot drift.

    Generated by scripts/build-lockup.mjs. The wordmark is outlined into paths rather than
    set as <text>, which is what makes this file self-contained: no font is downloaded, none
    is shipped, and it renders identically wherever it lands — a browser, a print shop's
    layout tool, a t-shirt printer. Set as text it would silently fall back to whatever font
    the viewer happened to have, which is the incoherence this is meant to prevent.

    Type is ${provenance}, used at build time only to produce the outlines below.

    The mark geometry is shared with static/icons/*.svg. Change it in one place and change it
    in all of them.
  -->
  <g fill="${fg}">
    <g transform="translate(${markX.toFixed(1)} ${markY.toFixed(1)}) scale(${scale.toFixed(4)})">
      <g fill="none" stroke="${fg}" stroke-width="${MARK.stroke}" stroke-linecap="round">
${MARK.d.map((d) => `        <path d="${d}" />`).join('\n')}
      </g>
      <circle cx="${MARK.bud.cx}" cy="${MARK.bud.cy}" r="${MARK.bud.r}" />
    </g>
    <path transform="translate(${(pad + scaledMarkW + gap - box.x1).toFixed(1)} ${wordY.toFixed(1)})" d="${wordD}" />
  </g>
</svg>
`;

writeFileSync(join(here, '..', 'static', 'lockup.svg'), svg('#1f6f4a'));
writeFileSync(join(here, '..', 'static', 'lockup-inverse.svg'), svg('#ffffff'));
console.log(
	`lockup ${(totalW + pad * 2).toFixed(0)}x${(totalH + pad * 2).toFixed(0)}  gap ${gap.toFixed(1)}  mark ${scaledMarkW.toFixed(0)}x${targetMarkH.toFixed(0)}`
);
